name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild.exe bucket.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: x64/Release

  test:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: x64/Release

    - name: Run tests
      run: x64/Release/test.exe
